from State.HelpDeskState import HelpDeskState
from Utils.VectorStore import get_vector_store
from langchain_core.documents import Document
from Utils.Logger import get_logger

logger = get_logger("RETRIEVE")

def retrieve_node(state: HelpDeskState):
    """
    Retrieves relevant IT manuals from ChromaDB using semantic search 
    and dynamic metadata filtering.
    """
    logger.info("Retrieving documents from vector store")
    
    # 1. Extract search parameters from state
    # We prioritize tretrieve_nodehe 'search_query' generated by the AnalyzerNode
    query = state.get("search_query") or state.get("question")
    category = state.get("category")
    # app_name = state.get("application_name")
    
    # 2. Build the ChromaDB Metadata Filter
    # Chroma uses a dictionary for simple equality filters.
    # If using multiple filters, Chroma usually requires an '$and' operator.
    search_filter = {}
    
    filters = []
    if category:
        filters.append({"category": category})
    
    # if app_name and app_name.lower() != "none":
    #     filters.append({"application_name": app_name})

    # Construct the final filter object
    if len(filters) > 1:
        search_filter = {"$and": filters}
    elif len(filters) == 1:
        search_filter = filters[0]
    else:
        search_filter = None

    logger.info(f"Optimized Query: '{query}'")
    logger.info(f"Active Filters: {search_filter}")

    try:
        # 3. Connect to our persistent Azure-powered Vector Store
        vector_store = get_vector_store()
        
        # 4. Perform Similarity Search
        # k=4 retrieves the top 4 most relevant technical chunks
        raw_docs = vector_store.similarity_search(
            query=query, 
            k=4, 
            filter=search_filter
        )
        
        # 5. Format for the HelpDeskState (List of Dicts)
        formatted_docs = []
        for doc in raw_docs:
            formatted_docs.append({
                "content": doc.page_content,
                "metadata": doc.metadata
            })
            source = doc.metadata.get('source', 'Unknown Manual')
            logger.info(f"Match Found: {source}")
            
        if not formatted_docs:
            logger.info("No matches found in local Vector DB")

    except Exception as e:
        logger.error(f"Retrieval Error: {e}")
        formatted_docs = []
        
    # Return the findings to the graph state
    return {"documents": formatted_docs}